### ISSUE TITLE
B<>> converted incorrectly

### ISSUE THREAD

**Issue by ole-tange** [cuberat/Pod-POM-View-Restructured#14]
Foo B<>> bar B<baz>.                                                                      
                                                                                          
    Foo B<>>> bar B<baz>.                                                                     
                                                                                          
    Foo B<>>>> bar B<baz>.

Gives:

    Foo \ ****\ > bar \ **baz**\ .

    Foo \ ****\ >> bar \ **baz**\ .

    Foo \ ****\ >>> bar \ **baz**\ .

Should give:

    Foo \ **>**\  bar \ **baz**\ .

    Foo \ **>>**\  bar \ **baz**\ .

    Foo \ **>>>**\  bar \ **baz**\ .

**Comment by alexm** [comment]
In this case, pod2html gives the same result: the greater than signs after bold sequence. Which means that pod2rst is doing the right thing, AFAICS.

You should probably escape those, as in `E<gt>`, i.e:

```
Foo B<E<gt>> bar B<baz>.

Foo B<E<gt>E<gt>> bar B<baz>.

Foo B<E<gt>E<gt>E<gt>> bar B<baz>.
```

Can you confirm that it works for you too?

**Comment by ole-tange** [comment]
That works.

Thanks.
